-- ============================================================================
-- Lokale Seed-Datei (nur synthetische Fixtures)
-- ============================================================================
-- Diese Datei wird laut step0Baseline.revision2.md, Abschnitt 9, niemals automatisch
-- remote ausgerollt. Sie darf ausschliesslich klar erkennbare synthetische lokale
-- Testdaten enthalten -- keine echten Geschaefts-, Auth- oder Personendaten.
--
-- Die historischen Testnutzer/-daten aus legacy-migrations/006_seed_test_data.sql werden
-- NICHT automatisch hierher uebernommen; sie bleiben nur als historische Referenz erhalten.

-- ============================================================================
-- offers / offer_editions -- 5. Klasse Lerncamp (Layout_5_Klasse_Intensivkurs_Unterseite.html)
-- ============================================================================
-- Der frühere Platzhalter-Insert hier (0 Rappen, status='draft', wegen des ungelösten
-- Preiskonflikts CHF 950 vs. CHF 890) wurde am 23.07.2026 entfernt: Das Angebot hat inzwischen ein
-- vollständiges Fixture (fuenfKlasseLerncampSportferien, types/marketing.fixtures.ts) und eine
-- reguläre published-Zeile aus der additiven Migration
-- supabase/migrations/20260723..._seed_published_offer_editions.sql (regular_price_rappen=95000,
-- per Nutzer-Entscheid CHF 950). Ein zusätzlicher Insert hier für denselben
-- (offer_id, school_year)-Schlüssel würde jetzt den UNIQUE(offer_id, school_year)-Constraint
-- verletzen und jeden `db reset --local` brechen.
