-- ============================================================================
-- Lokale Seed-Datei (nur synthetische Fixtures)
-- ============================================================================
-- Diese Datei wird laut step0Baseline.revision2.md, Abschnitt 9, niemals automatisch
-- remote ausgerollt. Sie darf ausschliesslich klar erkennbare synthetische lokale
-- Testdaten enthalten -- keine echten Geschaefts-, Auth- oder Personendaten.
--
-- Die historischen Testnutzer/-daten aus legacy-migrations/006_seed_test_data.sql werden
-- NICHT automatisch hierher uebernommen; sie bleiben nur als historische Referenz erhalten.

-- ============================================================================
-- offers / offer_editions -- 5. Klasse Lerncamp (Layout_5_Klasse_Intensivkurs_Unterseite.html)
-- ============================================================================
-- Der frühere Platzhalter-Insert hier (0 Rappen, status='draft', wegen des ungelösten
-- Preiskonflikts CHF 950 vs. CHF 890) wurde am 23.07.2026 entfernt: Das Angebot hat inzwischen ein
-- vollständiges Fixture (fuenfKlasseLerncampSportferien, types/marketing.fixtures.ts) und eine
-- reguläre published-Zeile aus der additiven Migration
-- supabase/migrations/20260723..._seed_published_offer_editions.sql (regular_price_rappen=95000,
-- per Nutzer-Entscheid CHF 950). Ein zusätzlicher Insert hier für denselben
-- (offer_id, school_year)-Schlüssel würde jetzt den UNIQUE(offer_id, school_year)-Constraint
-- verletzen und jeden `db reset --local` brechen.

-- ============================================================================
-- courses / course_occurrences -- synthetische lokale Fixtures für die neue Admin-Maske
-- (app/(dashboard)/dashboard/kurse/auffrischungskurse). Getrennter Geschäftszweig ohne Bezug zu
-- intensivwoche_kurse; die zwei Standorte entsprechen den ab 23.07.2026 für neue Zeilen
-- verbindlichen COURSE_LOCATIONS (types/auffrischungskurs.ts). Rein lokal, keine Live-Daten.
-- ============================================================================
-- courses.id ist GENERATED BY DEFAULT AS IDENTITY -- explizite Werte sind ohne
-- "OVERRIDING SYSTEM VALUE" zulässig (das wäre nur für GENERATED ALWAYS nötig).
insert into public.courses (id, title, description, price, location, timezone, payment_method) values
  (9001, 'Auffrischungskurs Mathematik (Test)', 'Lokale Testdaten für die Admin-Maske.', 50, 'FFSH Zürich, Zollstrasse 17, 8005 Zürich', 'Europe/Zurich', 'Bar vor Ort'),
  (9002, 'Intensivkurs Deutsch (Test)', 'Lokale Testdaten für die Admin-Maske.', 130, 'Schaffhauserstrasse 2, 8400 Winterthur', 'Europe/Zurich', 'Bar vor Ort');

insert into public.course_occurrences (course_id, starts_at_utc, ends_at_utc) values
  (9001, '2026-09-01 07:00:00+00', '2026-09-01 08:00:00+00'),
  (9001, '2026-09-01 12:00:00+00', '2026-09-01 13:00:00+00'),
  (9002, '2026-09-15 11:00:00+00', '2026-09-15 14:00:00+00');
